{{- if .Values.gateway.ingress.enabled }}
{{- $fullName := include "secupi_gateway.name" . -}}
{{- $servicePort := .Values.gateway.port -}}
{{- $ingressPath := .Values.gateway.ingress.path -}}
{{- $ingressPathType := .Values.gateway.ingress.pathType -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1/Ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  {{- if .Values.gateway.ingress.suffix }}
  name: {{ .Release.Name }}-{{ .Values.gateway.ingress.suffix }}
  {{- else }}
  name: {{ $fullName }}
  {{- end }}
  labels:
    app: {{ include "secupi_gateway.label" . }}
    {{- include "secupi_common.labels" . | nindent 4 }}
  annotations:
{{ tpl (toYaml .Values.gateway.ingress.annotations) . | indent 4 }}
spec:
  {{- if .Values.gateway.ingress.ingressClassName }}
  ingressClassName: {{ .Values.gateway.ingress.ingressClassName }}
  {{- end -}}
{{- if .Values.gateway.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.gateway.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .Values.gateway.ingress.hosts  }}
  {{- range .Values.gateway.ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: {{ $ingressPathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
            pathType: {{ $ingressPathType }}
          {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
  {{- end -}}
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/Ingress" }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  {{- if .Values.gateway.ingress.suffix }}
  name: {{ .Release.Name }}-{{ .Values.gateway.ingress.suffix }}
  {{- else }}
  name: {{ $fullName }}
  {{- end }}
  labels:
    app: {{ include "secupi_gateway.label" . }}
    {{- include "secupi_common.labels" . | nindent 4 }}
  annotations:
{{ toYaml .Values.gateway.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.gateway.ingress.ingressClassName }}
  ingressClassName: {{ .Values.gateway.ingress.ingressClassName }}
  {{- end -}}
{{- if .Values.gateway.ingress.tls }}
  tls:
{{ tpl (toYaml .Values.gateway.ingress.tls) $ | indent 4 }}
{{- end }}
  rules:
  {{- if .Values.gateway.ingress.hosts  }}
  {{- range .Values.gateway.ingress.hosts }}
    - host: {{ tpl . $}}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
  {{- end }}
  {{- else }}
    - http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
          {{- if $ingressPath }}
            path: {{ $ingressPath }}
            {{- end }}
  {{- end -}}
{{- end }}
{{- end }}
