{{- if and (gt (int .Values.gateway.replicaCount) 1) .Values.gateway.podDisruptionBudget }}
{{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "secupi_gateway.name" . }}
  labels:
    app: {{ include "secupi_gateway.label" . }}
    {{- include "secupi_common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "secupi_gateway.label" . }}
  {{- if .Values.gateway.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.gateway.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  {{- if .Values.gateway.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.gateway.podDisruptionBudget.minAvailable }}
  {{- end }}
{{- end }}
