{{- if .Values.gateway.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.gateway.serviceAccount.name | default (include "secupi_service_account.name" .) }}
  {{- with .Values.gateway.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
